### ISSUE TITLE
如何理解why-not-waste-your-youth

### ISSUE THREAD

**Issue by shenjiefeng** [azalea/azalea.github.io#21]
为什么`不浪费`你的青春
还是为什么`不要浪费`你的青春

**Comment by azalea** [comment]
你好，这个问题其实可以直接在原文下面评论 
http://azaleasays.com/2015/09/06/why-not-waste-your-youth/
因为并不是源代码的问题 ;)

不过我就在这里解答好了。
英文标题直译就是“为什么不浪费你的青春”，当然正文解释了，这种所谓的浪费青春实际并不是浪费啦。
不用想太多，英文标题不过是个 slug 
[https://en.wikipedia.org/wiki/Slug_(publishing)](https://en.wikipedia.org/wiki/Slug_(publishing))

**Comment by lawlietfans** [comment]
英语渣突然开个脑洞^_^
前辈所言极是，受教了
